import os
import subprocess
import pytest


CUR_FOLDER = os.path.dirname(os.path.abspath(__file__))
STUNED_ROOT = os.path.dirname(CUR_FOLDER)


def get_python_binary():
    # on github everything is in the base env, but when debugging
    # we need to use the envs/stuned_env env
    conda_env = os.environ.get("CONDA_DEFAULT_ENV", "None")
    if conda_env != "None":
        assert os.path.exists(
            conda_env
        ), f"Conda env {conda_env} does not exist"
        python_binary = os.path.join(conda_env, "bin", "python3.10")
        assert os.path.exists(
            python_binary
        ), f"Python binary {python_binary} does not exist"
    else:
        python_binary = "python"
    return python_binary, conda_env


# @pytest.mark.skip(reason="Temporarily disabled")
def test_calling_scheduler():
    os.environ["PROJECT_ROOT_PROVIDED_FOR_STUNED"] = os.path.join(STUNED_ROOT)
    python_binary, conda_env = get_python_binary()
    cmd = f"{python_binary} -m stuned.run_from_csv"

    result = subprocess.run(cmd.split(), capture_output=True, text=True)
    assert "the following arguments are required: --csv_path" in result.stderr


# @pytest.mark.skip(reason="Temporarily disabled")
def test_imports_for_moved_to_stnd():
    """Test that the imports for moved to stnd are working."""
    from stuned.utility.configs import (
        make_csv_config,
        get_config,
        find_nested_keys_by_keyword_in_config,
        normalize_paths,
        prepare_config,
        HARDCODED_CONFIG,
        AUTOGEN_PREFIX,
        EXP_NAME_CONFIG_KEY,
        START_TIME_CONFIG_KEY,
        RUN_PATH_CONFIG_KEY,
        TYPE_KEY,
        ANY_KEY,
        NESTED_CONFIG_KEY_SEPARATOR,
    )
    from stuned.utility.helpers_for_main import (
        parse_args,
        get_diff_with_unstaged_changes,
        prepare_wrapper_for_experiment,
        define_env_vars,
        SCRATCH_LOCAL,
        SCRATCH_VAR_NAME,
    )
    from stuned.utility.logger import (
        # Constants
        PROGRESS_FREQUENCY,
        INDENT,
        LOGGER_ARG_NAME,
        CONTROL_PREFIX,
        CONTROL_SUFFIX,
        CONTROL_SEPARATOR,
        DEFAULT_TEXT_STYLE,
        BOLD_TEXT_STYLE,
        BLACK_COLOR_CODE,
        RED_COLOR_CODE,
        GREEN_COLOR_CODE,
        BLUE_COLOR_CODE,
        PURPLE_COLOR_CODE,
        CYAN_COLOR_CODE,
        WHITE_COLOR_CODE,
        DEFAULT_EXPERIMENT,
        DEFAULT_NAME_PREFIX,
        LOG_PREFIX,
        INFO_PREFIX,
        ERROR_PREFIX,
        MAX_LINE_LENGTH,
        SEPARATOR,
        STATUS_CSV_COLUMN,
        RUN_FOLDER_CSV_COLUMN,
        WALLTIME_COLUMN,
        SUBMITTED_STATUS,
        RUNNING_STATUS,
        COMPLETED_STATUS,
        FAIL_STATUS,
        WHETHER_TO_RUN_COLUMN,
        OUTPUT_CSV_KEY,
        PATH_KEY,
        INITIAL_CSV_KEY,
        ROW_NUMBER_KEY,
        GDRIVE_FOLDER_KEY,
        STDOUT_KEY,
        STDERR_KEY,
        WANDB_URL_COLUMN,
        WANDB_QUIET,
        WANDB_INIT_RETRIES,
        WANDB_SLEEP_BETWEEN_INIT_RETRIES,
        PROJECT_KEY,
        TB_CREDENTIALS_FIELDS,
        TB_CREDENTIALS_DEFAULT,
        TB_URL_COLUMN,
        TB_LOG_FOLDER,
        TB_TIME_TO_LOG_LAST_EPOCH,
        TB_OUTPUT_BEFORE_LINK,
        TB_OUTPUT_AFTER_LINK,
        TB_OUTPUT_SIZE_LIMIT,
        READ_BUFSIZE,
        TENSORBOARD_FINISHED,
        MAX_TIME_BETWEEN_TB_LOG_UPDATES,
        MAX_TIME_TO_WAIT_FOR_TB_TO_SAVE_DATA,
        LOGGING_CONFIG_KEY,
        DEFAULT_SPREADSHEET_ROWS,
        DEFAULT_SPREADSHEET_COLS,
        DEFAULT_SPREADSHEET_NAME,
        DEFAULT_GAUTH_FOLDER,
        DEFAULT_GOOGLE_CREDENTIALS_PATH,
        DEFAULT_GOOGLE_SERVICE_CREDENTIALS_PATH,
        DEFAULT_REFRESH_GOOGLE_CREDENTIALS,
        URL_ID_RE,
        URL_KEY_RE,
        URL_SPREADSHEET_RE,
        URL_FILE_RE,
        URL_FOLDER_RE,
        DEFAULT_GOOGLE_SCOPES,
        FILE_TYPES_ALLOWED_TO_SYNC,
        SPREADSHEETS_URL,
        WORKSHEET_SEPARATOR,
        DELTA_PREFIX,
        SLURM_PREFIX,
        PREFIX_SEPARATOR,
        OLD_PREFIX,
        PREV_RUN_FOLDER_KEY,
        PLACEHOLDERS_FOR_DEFAULT,
        DAEMON_SLEEP_TIME,
        TIME_TO_LOSE_LOCK_IF_CONCURRENT,
        # Functions
        make_string_style,
        infer_logger_from_args,
        retrier_factory_with_auto_logger,
        BaseLogger,
        RedneckLogger,
        sync_output_with_remote,
        make_logger,
        make_logger_with_tmp_output_folder,
        update_and_move_logger_output_folder,
        store_profiler_results,
        dump_profiler_results,
        handle_exception,
        try_to_log_in_csv,
        try_to_log_in_csv_in_batch,
        try_to_sync_csv_with_remote,
        try_to_log_in_wandb,
        try_to_log_in_tb,
        insert_char_before_max_width,
        redneck_logger_context,
        assert_tb_credentials,
        run_tb_folder_listener,
        get_tb_url,
        delete_run_folders,
        tb_log,
        extract_id_from_spreadsheet_url,
        extract_id_from_gdrive_url,
        extract_by_regex_from_url,
        GspreadClient,
        make_gspread_client,
        build_spreadsheet_dict,
        extract_csv_name_from_path,
        init_wandb_run,
        GdriveClient,
        make_gdrive_client,
        make_google_auth,
        sync_local_file_with_gdrive,
        get_gdrive_file_by_url,
        log_csv_for_concurrent,
        RedneckProgressBar,
        make_progress_bar,
        fetch_csv,
        get_default_csv_folder,
        try_to_upload_csv,
        make_prefixed_column_name,
        make_delta_column_name,
        make_slurm_column_name,
        log_info,
    )
    from stuned.utility.utils import (
        # Constants
        MAX_BUFFER_SIZE,
        SYSTEM_PLATFORM,
        DEFAULT_HASH_SIZE,
        DEFAULT_EXPERIMENTS_FOLDER,
        PROFILER_GROUP_BY_STACK_N,
        PROFILER_OUTPUT_ROW_LIMIT,
        DEFAULT_FILE_CHUNK_SIZE,
        EMPTY_CSV_TOKEN,
        DEFAULT_ENV_NAME,
        TEST_ENV_NAME,
        BASHRC_PATH,
        NEW_SHELL_INIT_COMMAND,
        FLOATING_POINT,
        NAME_SEP,
        NAME_NUMBER_SEPARATOR,
        NULL_CONTEXT,
        PROJECT_ROOT_ENV_NAME,
        DEFAULT_SLEEP_TIME,
        DEFAULT_NUM_ATTEMTPS,
        MAX_RETRIES_ERROR_MSG,
        DEFAULT_INDENT_IN_JSON,
        LIST_START_SYMBOL,
        LIST_END_SYMBOL,
        DELIMETER,
        QUOTE_CHAR,
        ESCAPE_CHAR,
        INF,
        TOL,
        EXPONENTIAL_SYMBOLS,
        PLT_ROW_SIZE,
        PLT_COL_SIZE,
        PLT_PLOT_HEIGHT,
        PLT_PLOT_WIDTH,
        ENV_VAR_RE,
        # Classes
        ChildrenForPicklingPreparer,
        SetEncoder,
        AttrDict,
        TimeStampEventHandler,
        # Functions
        object_attributes,
        read_yaml,
        apply_random_seed,
        get_current_time,
        raise_unknown,
        append_dict,
        check_element_in_iterable,
        check_dict,
        run_cmd_through_popen,
        runcmd,
        compute_dicts_diff,
        randomly_subsample_indices_uniformly,
        deterministically_subsample_indices_uniformly,
        get_device,
        get_model_device,
        get_project_root_path,
        get_stuned_root_path,
        make_unique_run_name,
        get_current_run_folder,
        get_hash,
        get_value_from_config,
        log_or_print,
        error_or_print,
        read_checkpoint,
        save_checkpoint,
        prepare_for_pickling,
        prepare_for_unpickling,
        make_checkpoint_name,
        get_leaves_of_nested_dict,
        update_dict_by_nested_key,
        apply_func_to_dict_by_nested_key,
        extract_profiler_results,
        check_equal_shape,
        move_folder_contents,
        remove_all_but_subdirs,
        remove_file_or_folder,
        is_nested_dict,
        ensure_separator_after_folder,
        compute_file_hash,
        get_hasher,
        get_hostname,
        remove_filename_extension,
        range_for_each_group,
        coefficients_for_bases,
        error_callback,
        deterministic_subset,
        compute_proportion,
        make_autogenerated_config_name,
        save_as_yaml,
        write_into_csv_pd,
        write_into_csv_with_column_names,
        count_rows_in_file,
        remove_elements_from_the_end,
        itself_and_lower_upper_case,
        decode_strings_in_dict,
        decode_val_from_str,
        replace_many_by_one,
        str_is_number,
        parse_float_or_int_from_string,
        escape_all_chars_in_string,
        parse_list_from_string,
        read_csv_as_dict,
        read_csv_as_dict_pd,
        normalize_string_path,
        normalize_path,
        read_json,
        dicts_with_non_intersecting_keys,
        is_number,
        assert_two_values_are_close,
        bootstrap_by_key_subname,
        find_by_subkey,
        get_system_root_path,
        prepare_factory_without_args,
        raise_func,
        retrier_factory,
        pretty_json,
        touch_file,
        cat_or_assign,
        kill_processes,
        read_old_checkpoint,
        read_model_from_old_checkpoint,
        make_file_lock,
        check_duplicates,
        has_nested_attr,
        get_nested_attr,
        set_nested_attr,
        write_csv_dict_to_csv,
        write_csv_dict_to_csv_pd,
        expand_csv,
        instantiate_from_config,
        folder_still_has_updates,
        as_str_for_csv,
        check_consistency,
        aggregate_tensors_by_func,
        func_for_dim,
        parse_name_and_number,
        show_images,
        imshow,
        get_cmap,
        compute_tensor_cumsums,
        compute_unique_tensor_value,
        prune_list,
        get_with_assert,
        properties_diff,
        get_even_from_wrapped,
        add_custom_properties,
        invert_dict,
        load_from_pickle,
        extract_list_from_huge_string,
        apply_pairwise,
        download_file,
        extract_tar_to_folder,
        create_tar_from_folder,
        get_filename_from_url,
        download_and_extract_tar,
        optionally_make_dir,
    )
    from stuned.utility.imports import (
        PACKAGE_SEPARATOR,
        FROM_CLASS_KEY,
        LazyModuleWrapper,
        is_bulitin_name,
        importlib_lazy_import,
        lazy_import,
        _LazyModule,
        make_lazy_module,
        pop_all_modules_by_filter,
        import_from_string,
        make_from_class_ctor,
        update_enums_in_config,
    )
    from stuned.local_datasets.utils import (
        CHECK_FILE_HASH,
        EMPTY_URL,
        YANDEX_API_ENDPOINT,
        H5_EXTENSION,
        TRAIN_KEY,
        VAL_KEY,
        SCALING_FACTOR,
        DatasetWrapperWithTransforms,
        SingleDataloaderWrapper,
        ManyDataloadersWrapper,
        ChainingIteratorsWrapper,
        DropLastIteratorWrapper,
        CachingDatasetWrapper,
        DatasetWrapperWithIndex,
        make_dataset_wrapper_with_transforms,
        make_default_data_path,
        fetch_data,
        convert_dataset_to_tensor,
        convert_dataset_to_tensor_generator,
        make_contents_as_in_subfolder,
        do_fetch_dataset_as_file,
        download_file_by_link,
        download_file_by_yadisk_link,
        assert_dataset_as_file,
        randomly_subsampled_dataloader,
        subsample_dataloader_randomly,
        get_dataloader_init_args_from_existing_dataloader,
        wrap_dataloader,
        get_generic_train_eval_dataloaders,
        uniformly_subsample_dataset,
        show_dataloader_first_batch,
        show_images_batch,
        make_named_labels_batch,
        chain_dataloaders,
        make_sampler,
        get_base_dataset,
        make_caching_dataset,
        make_dataset_wrapper_with_index,
        unnormalize,
        tensor_for_matplotlib,
    )
